### ISSUE TITLE
[Docs] `README` not rendering properly

### ISSUE THREAD

**Issue by leycec** [brendanxwhitaker/asta#5]
@langfield, it's you! You quietly slipped this `>>> from asta import symbols` line into beartype/beartype#82. I rubbed my stubbly chin thoughtfully. Then I googled furiously. Five minutes later, I arrived here – only to find your reStructuredText (reST) both here and on [PyPI](https://pypi.org/project/asta) not rendering quite right. My stricken panic ensues.

Okay. Your reST isn't rendering at *all*, actually: e.g.,

```
+----+
|asta|
+----+

Shape annotations for numpy arrays and pytorch/tensorflow tensors.

Introduction
------------
```

## Let Me Now Do Things for You

There are two orthogonal solutions here:

* **Render reST on GitHub.** This is easy! Just rename `README` to `README.rst`. GitHub should then automatically render your `README.rst` as reStructuredText.
* **Render reST on PyPI.** This is slightly less easy, but still not *too* hard. Just add a new top-level `setup.cfg` file with contents resembling:

```
[metadata]

# Relative filename of the file defining this project's license.
license_file = LICENSE

# Relative filename of the file describing this project.
long_description = file: README.rst
long_description_content_type = text/x-rst; charset=UTF-8
```

**That's it.** Thanks again for all the voluminous issue churn on the @beartype tracker. You rock the open-source QA tensor-typing community. *Strange face in the clouds approves.* :face_in_clouds:

**Comment by langfield** [comment]
Thanks so much for taking a look at the ghost town that is this project, haha! Actually I didn't intend for this to be reST while writing it, it's just a plaintext README.

Perhaps one day this could be refactored into a library that sits on top of beartype, for supporting dependently-typed tensors. It would take a fair bit of work to do this, though. There is the bones of an entire `typeguard`-like checker for all ordinary python containers and types as well, buried somewhere in here. It was very slow, though, because I did not have the brilliant idea of doing randomized O(1) checking.

All that would need to be excised and then the symbolic computation stuff would have to be revamped.

And of course I'd need to rewrite the README so that it is rendered, because that seems to be a requirement for your library to gain use nowadays.

For now, though, it's **won't fix**, until I come back to this project. Sorry!

**Comment by leycec** [comment]
Oh, **no worries whatsoever.** I saw the double-backticked identifiers that are the classic hallmark of reST (e.g., \`\`Array\`\`) and sorta just assumed you were neck-deep into the perfidious reST hole. But it's all good.

There's some phenomenally intriguing magic going on here, too:

> There is the bones of an entire `typeguard`-like checker for all ordinary python containers and types as well, buried somewhere in here. ...and then the symbolic computation stuff...

Jesus on a chocolate stick. I *never* thought to integrate SymPy with type-checking. In hindsight, I see the practical applications – and I'm still not sure I want to go there.

It'd be spell-binding to liberate the novel algorithms you've got going on in this codebase. Until then, let's close this on behalf of your precious free time. :smiley_cat:
